config/routes.rb
Challenge::Application.routes.draw do
  get "tweets/index"

  get "tweets/:id", to: "tweets#show", as: "tweets_show"

  root :to => 'tweets#index'
end

app/models/storing.rb
class Storing
  include Mongoid::Document
  field :message, type: String
  field :latitude, type: Float
  field :logitude, type: Float
  field :user_name, type: String
end

app/models/user_tweet.rb
class UserTweet
  include Mongoid::Document
  field :message, type: String
  field :latitude, type: Float
  field :logitude, type: Float
  field :user_name, type: String

  index({ "latitude" => "2d" })
  index({ "logitude" => "2d" })
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
  	if params[:lat]
  		@tweets = UserTweet.where(:latitude => params[:lat] , :logitude => params[:log]).paginate(:page => params[:page], :per_page => 10)
  	else
  		@tweets = UserTweet.paginate(:page => params[:page], :per_page => 10)
  	end
  end

  def show
  	@tweet = UserTweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<%= form_tag do %>
<p>Latitude: <%= text_field_tag :lat %>
Longitude: <%= text_field_tag :log %>
<%= submit_tag "Search " %></p>
<% end %>
<table>
<tr>
<th>Username</th>
<th>Message</th>
<th>Latitude</th>
<th>Longitude</th>
<th>Show Map</th></tr>
<% @tweets.each do |t| %>
<tr>
	<td>
		<%= t.user_name %>
	</td>
	<td><%= t.message %></td>
	<td><%= t.latitude %></td>
	<td><%= t.logitude %></td> 
	<td><%= link_to "Show Map", tweets_show_path(t) %></td>
</tr>
<% end %>
</table>
<%= will_paginate @tweets %>

app/views/tweets/show.html.erb
<p>UserName : <%= @tweet.user_name %></p>
<p>Tweet : <%= @tweet.message %>

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@tweet.latitude},#{@tweet.logitude}&markers=#{@tweet.latitude},#{@tweet.logitude}&zoom=7&size=640x400&key=AIzaSyAFa4YnkGQC07Iqc--e91UsecYt88h1Bew",
              class: 'img-fluid img-rounded', alt: "#{@tweet.user_name} on the map"%>